  prometheus:
    image: prom/prometheus:latest
    container_name: monitoring_prometheus
    restart: unless-stopped
    volumes:
#      - ./data/prometheus/config:/etc/prometheus/
      - ./data/prometheus/data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
#      - '-storage.local.path=/prometheus'
#      - '-alertmanager.url=http://alertmanager:9093'
    expose:
      - 9090
    ports:
      - 9090:9090
    links:
      - spring-app-monitoring:spring-app-monitoring
#      - node-exporter:node-exporter

#  node-exporter:
#    image: prom/node-exporter:latest
#    container_name: monitoring_node_exporter
#    restart: unless-stopped
#    expose:
#      - 9100

#  cadvisor:
#    image: google/cadvisor:latest
#    container_name: monitoring_cadvisor
#    restart: unless-stopped
#    volumes:
#      - /dev/disk/:/dev/disk:ro
#      - /:/rootfs:ro
#      - /var/run:/var/run:rw
#      - /sys:/sys:ro
#      - /var/lib/docker/:/var/lib/docker:ro
#    expose:
#      - 8080
#    ports:
#      - 8080:8080
  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana/data:/var/lib/grafana
      - ./data/grafana/provisioning/:/etc/grafana/provisioning 
    links: 
      - prometheus:prometheus

  spring-app-monitoring:
    image: app-monitor/spring-app-monitoring:latest
    container_name: app-monitor
    restart: unless-stopped
    ports:
      - 8061:8061
    volumes:
      - ./data/app:/files
